name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or "master", depending on your setup

permissions:
  contents: write # Grants permission to create or update deployment branches like gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Announce Event
        run: echo "🎉 Workflow triggered by: ${{ github.event_name }} (branch: ${{ github.ref }})"

      - name: Fetch Repository Content
        run: echo "Cloning repository…"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Confirm Node.js Installation
        run: node --version && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build  # vite builds the output into a /dist folder

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
